"""Biological assembly generation via gemmi.

Bio.PDB -- the backend behind every other module in this package
(models.py/io.py/selection.py/geometry.py/...) -- only ever gives you the
asymmetric unit exactly as deposited. It has no way to expand a PDB
REMARK 350 or mmCIF _pdbx_struct_assembly_gen block into the actual
biological unit (e.g. a crystallographic monomer that's really a
dimer/tetramer in solution, generated by applying a documented symmetry
operation). This was a known gap flagged back when this project's spec
was first drafted and left unaddressed until now.

gemmi (https://gemmi.readthedocs.io/) is free, pip-installable
(`pip install -e ".[assembly]"`), and is used here for exactly this one
capability. Everything else in ProteinExplorer stays on the
Bio.PDB-based data model -- this module's job is narrow: read a file
with gemmi, expand the requested assembly, and write the result back out
as an ordinary PDB/mmCIF file that `io.load_structure()` (Bio.PDB-based,
same as everywhere else in this package) can then read like any other
structure, so the rest of the toolkit needs no changes to work with an
assembly once it's been generated.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


class GemmiNotAvailableError(RuntimeError):
    pass


def _require_gemmi():
    try:
        import gemmi
    except ImportError as exc:
        raise GemmiNotAvailableError(
            "gemmi is not installed. Install it with `pip install -e \".[assembly]\"` "
            "(or `pip install gemmi`) -- it's free/open-source and pip-installable, "
            "no license needed."
        ) from exc
    return gemmi


@dataclass
class AssemblyInfo:
    name: str
    oligomeric_details: str | None  # e.g. "MONOMERIC", "DIMERIC" -- as documented in the file, when present
    chains_involved: list[str]
    n_operators: int


def list_assemblies(path: str | Path) -> list[AssemblyInfo]:
    """List the biological assemblies documented in a structure file
    (from PDB REMARK 350 or mmCIF _pdbx_struct_assembly), without
    generating any of them."""
    gemmi = _require_gemmi()
    structure = gemmi.read_structure(str(path))

    infos = []
    for assembly in structure.assemblies:
        chains: list[str] = []
        n_operators = 0
        for generator in assembly.generators:
            chains.extend(generator.chains)
            n_operators += len(generator.operators)
        details = str(assembly.oligomeric_details) if assembly.oligomeric_details else None
        infos.append(
            AssemblyInfo(
                name=assembly.name, oligomeric_details=details,
                chains_involved=sorted(set(chains)), n_operators=n_operators,
            )
        )
    return infos


@dataclass
class AssemblyResult:
    assembly_name: str
    chains_before: list[str]
    chains_after: list[str]
    n_atoms_after: int


_HOW_TO_NAME = {
    "number": "AddNumber",   # A -> A1, A2, ...  (default: never collides)
    "short": "Short",        # reuses short auto-generated chain names
    "duplicate": "Dup",      # keeps the original chain ID (chains can collide)
}


def generate_assembly(
    input_path: str | Path,
    output_path: str | Path,
    assembly_name: str | None = None,
    how: str = "number",
) -> AssemblyResult:
    """Expand a documented biological assembly and write it to
    `output_path` (format inferred from the extension, same convention as
    io.save_structure elsewhere in this package).

    assembly_name=None uses the file's first documented assembly (usually
    what you want -- the first assembly is conventionally the author- or
    software-recommended biological unit). Use `list_assemblies()` first
    if a file documents more than one and you need a specific one.

    how="number" (default) renames copied chains to avoid collisions
    (A -> A1, A2, ...); "short" reuses gemmi's compact auto-naming;
    "duplicate" keeps original chain IDs, which can collide across
    copies -- only use it if you're handling that yourself downstream.
    """
    gemmi = _require_gemmi()
    if how not in _HOW_TO_NAME:
        raise ValueError(f"Unknown how={how!r} (expected one of {sorted(_HOW_TO_NAME)})")

    structure = gemmi.read_structure(str(input_path))
    if not structure.assemblies:
        raise ValueError(f"{input_path} has no documented biological assembly (REMARK 350/_pdbx_struct_assembly)")

    name = assembly_name or structure.assemblies[0].name
    chains_before = [c.name for c in structure[0]]

    how_enum = getattr(gemmi.HowToNameCopiedChain, _HOW_TO_NAME[how])
    structure.transform_to_assembly(name, how_enum)

    chains_after = [c.name for c in structure[0]]
    n_atoms_after = sum(1 for _ in structure[0].all())

    output_path = Path(output_path)
    if output_path.suffix in (".cif", ".mmcif"):
        structure.make_mmcif_document().write_file(str(output_path))
    else:
        structure.write_pdb(str(output_path))

    return AssemblyResult(
        assembly_name=name, chains_before=chains_before,
        chains_after=chains_after, n_atoms_after=n_atoms_after,
    )
