"""External 3D viewer integration (spec section "View").

Launches an already-installed viewer (PyMOL, ChimeraX, or VMD) on a
structure file, optionally alongside a script (e.g. one generated by
`prot map`). This is inherently external-tool-only -- there's no
meaningful dependency-free substitute for "open a GUI 3D viewer" -- so,
like predict.py and model.py's homology command, this raises a clear
ViewerNotAvailableError with install pointers when the chosen tool isn't
found, rather than attempting a fake substitute.

Viewers are GUI applications, so `launch()` starts them as a detached
background process (non-blocking) rather than waiting for them to exit.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

_VIEWER_BINARY_CANDIDATES: dict[str, list[str]] = {
    "pymol": ["pymol"],
    "chimerax": ["chimerax", "ChimeraX"],
    "vmd": ["vmd"],
}

_INSTALL_HINTS: dict[str, str] = {
    "pymol": "https://pymol.org/",
    "chimerax": "https://www.cgl.ucsf.edu/chimerax/",
    "vmd": "https://www.ks.uiuc.edu/Research/vmd/",
}


class ViewerNotAvailableError(RuntimeError):
    pass


class ViewError(ValueError):
    pass


def viewer_binary(tool: str) -> str | None:
    candidates = _VIEWER_BINARY_CANDIDATES.get(tool)
    if candidates is None:
        raise ViewError(f"Unknown viewer: {tool!r} (expected one of {sorted(_VIEWER_BINARY_CANDIDATES)})")
    for candidate in candidates:
        found = shutil.which(candidate)
        if found is not None:
            return found
    return None


def build_command(tool: str, structure_path: str | Path, script_path: str | Path | None = None) -> list[str]:
    """Build the command line to launch `tool` on `structure_path`,
    optionally running `script_path` (e.g. from `prot map`) afterward."""
    binary = viewer_binary(tool)
    if binary is None:
        hint = _INSTALL_HINTS.get(tool, "")
        raise ViewerNotAvailableError(
            f"{tool} executable not found on PATH."
            + (f" Install it from {hint}" if hint else "")
            + " -- there is no dependency-free substitute for viewing a structure."
        )

    structure_path = str(structure_path)
    if tool == "pymol":
        cmd = [binary, structure_path]
        if script_path is not None:
            cmd.append(str(script_path))
        return cmd
    if tool == "chimerax":
        cmd = [binary, structure_path]
        if script_path is not None:
            cmd.append(str(script_path))
        return cmd
    if tool == "vmd":
        cmd = [binary, structure_path]
        if script_path is not None:
            cmd += ["-e", str(script_path)]
        return cmd
    raise ViewError(f"Unknown viewer: {tool!r}")  # pragma: no cover - viewer_binary already validated tool


def launch(
    tool: str,
    structure_path: str | Path,
    script_path: str | Path | None = None,
) -> subprocess.Popen:
    """Start the viewer as a detached background process (non-blocking --
    GUI applications aren't meant to be waited on)."""
    cmd = build_command(tool, structure_path, script_path)
    return subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, start_new_session=True)
